#!/bin/sh
# Backup the installation directoty

# tar cvJf /tmp/ShellDB.$(date +%F).tar.xz -C /opt `ls --format single-column ../.. | grep -i ShellDB-`

tar cvJf /tmp/ShellDB.$(date +%F).tar.xz -C ../.. ShellDB
