#!/usr/bin/perl
# About the ShellDB
#
# George Bouras, Joanna Ntzougani
# george.mpouras@yandex.com

use FindBin;
use lib "$FindBin::Bin/../lib_perl";
use shelldb;

$output->{version} = $shelldb::VERSION;

open	FILE, '<', "$FindBin::Bin/../config/shelldb.cfg" or Exit(31, "Could not read configuration file because $!");
while (<FILE>) {
my ($k,$v) = $_ =~/^([^=]+)=(.+?)\s*$/ or next;
$v=~s/"//g;
if ($k eq 'build_date') { $output->{'Build date'}=$v }
if ($k eq 'developers') { $output->{'Developers'}=[ split /\s*(?:,|;|\|)\s*/, $v ]  }
}
close FILE;

$/ = undef;
open FILE, '<', "$FindBin::Bin/../LICENSE" or Exit(30, "Could not read LICENSE");
$output->{license} = <FILE>;
close FILE;

&Exit