#!/usr/bin/perl
# About the ShellDB
#
# George Bouras, Joanna Ntzougani
# george.mpouras@yandex.com

use FindBin;
use lib "$FindBin::Bin/../lib_perl";
use shelldb;

$output->{version} = $shelldb::VERSION;
$output->{license} = 'ShellDB is a fast and minimal document database. Copyright (C) 2018 George Bouras, georgios.mpouras@gmail.com . This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program.  If not, see <https://www.gnu.org/licenses>';

open	FILE, '<', "$FindBin::Bin/../config/shelldb.cfg" or Exit(30, "Could not read configuration file because $!");
while (<FILE>) {
my ($k,$v) = $_ =~/^([^=]+)=(.+?)\s*$/ or next;
$v=~s/"//g;
if ($k eq 'build_date') { $output->{'Build date'}=$v }
if ($k eq 'developers') { $output->{'Developers'}=[ split /\s*(?:,|;|\|)\s*/, $v ]  }
}
close FILE;
&Exit