#!/usr/bin/perl
# close a database
# The database is not deleted.
# You can open it if you want to re use it
#
# George Bouras
# george.mpouras@yandex.com

use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib_perl";
use shelldb;
use dbadmin;

if (exists $input->{db}) {
$input->{db} =~s/([^?*]+)/\Q$1\E/g;
$input->{db} =~s|\?|.|g;
$input->{db} =~s|\*+|.*?|g;
$input->{db} = qr/^$input->{db}$/i
}
else {
Exit(270, 'key db is missing from your input')
}

$output->{database}=[];
my $found;

opendir DIR, $datadir or Exit(271, "Could not list databases because $!");
while (my $db = readdir DIR) {
next unless ( ($db =~ $input->{db}) && (-d "$datadir/$db/metadata") && (-d "$datadir/$db/storage") );
$found=1;
next unless dbadmin::IsItMounted("$datadir/$db/data");

	foreach (qw/data snapshots/) {
	@{$output}{qw/error_code error_message/} = dbadmin::Umount("$datadir/$db/$_");
	&Exit if $output->{error_code};
	}

@{$output}{qw/error_code error_message/} = dbadmin::Losetup_detach("$datadir/$db");
&Exit if $output->{error_code};
push @{$output->{database}}, $db
}
closedir DIR;
@{$output}{'error_code','error_message'}=(272,'No matching database') unless $found;
&Exit