#!/usr/bin/perl
# Checks if a keys exist, Example of POST request (json)
# 
#	{ "db" : "SomeDB", "key" : "/Some/key" }
#
# George Bouras
# george.mpouras@yandex.com

use lib '/opt/shelldb/lib_perl';
use shelldb;

exists $input->{$_} || Exit(2, "key \"$_\" is missing from your input") foreach qw/db key/;
-d "$datadir/$input->{db}/data" || Exit 37,"The database $input->{db} does not exist";
$input->{key} =~s/^\/*(.*?)\/*$/$1/;

if		(-d "$datadir/$input->{db}/data/$input->{key}") { @{$output}{'exist','holdvalues'}=(1,0) }
elsif	(-f "$datadir/$input->{db}/data/$input->{key}") { @{$output}{'exist','holdvalues'}=(1,1) }
else	{ @{$output}{'exist','holdvalues'}=(0,0)	}

Exit