#!/usr/bin/perl
# insert/update records. POST Example
# 
#	{
#	"db"	: "DB1",			The selected database
#	"append": false,			true/false false if missing
#	"data"	: { "k1" : "v2" }	data to store (as json)
#	}
#
# George Bouras
# george.mpouras@yandex.com

use strict;
use warnings;
use lib '/opt/shelldb/lib_perl';
use shelldb;

exists $input->{$_} || Exit(2, "key $_ is missing from your input") foreach qw/db data/;
-d "$datadir/$input->{db}/data" || Exit(13, "The database $input->{db} does not exist");


my $append	= exists $input->{append} ? $input->{append}=~/(?i)true|y/ ? 1:0:0;
my $mode	= $append ? '>>:utf8' : '>:utf8';
my $dir;
my $file;
my %AllowList;
@{$output}{'keys','values'}=(0,0);


sub CreateDir {
my @Mkdir = split /\/+/, $_[0];
return $_[0] unless @Mkdir;
splice(@Mkdir, 0, 2, "/$Mkdir[1]") if (($Mkdir[0] eq '') && (scalar @Mkdir > 0));
my $i;
for ($i=$#Mkdir;$i>=0;$i--)		{ last if -d join '/', @Mkdir[0..$i] }
for (my $j=$i+1;$j<@Mkdir;$j++)	{ mkdir join('/', @Mkdir[0 .. $j]) or return undef }
$_[0]
}


sub Walker {
my $data=shift;
if		(ref $data eq 'SCALAR')	{ Walker(${$data}, @_) }
elsif	(ref $data eq 'ARRAY')	{ Walker($_, @_)				for @$data }
elsif	(ref $data eq 'HASH')	{ Walker($data->{$_}, @_, $_)	for keys %$data }

	else {
	$data // return;
	$file= @_ ? pop @_ : 'default';
	$dir = join '/', "$datadir/$input->{db}/data", @_;
	$data=~s/\s*$//;
	unless (-d $dir) {CreateDir $dir or Exit(14, "Could not create dir $dir because $!"); $output->{keys}++ }

		unless ($append) {

			if (exists $AllowList{"$dir/$file"}) {
			$mode = '>>:utf8'
			}
			else {
			$mode = '>:utf8';
			$AllowList{"$dir/$file"}=undef;
			$output->{keys}++
			}
		}

	open  FILE, $mode, "$dir/$file" or Exit(16, "Could not create file $dir/$file because $!");
	print FILE "$data\n";
	close FILE;
	$output->{values}++
	}
}


Walker $input->{data};
Exit